### ISSUE TITLE
deprecated by which project?

### ISSUE THREAD

**Issue by cipy** [hotosm/oam-server-tiler#12]
Hi there,

This repo/code is labeled as DEPRECATED: OAM Server Tiler

Question: if this is deprecated, which tiler is OAM using these days?

Thanks,
Ciprian

**Comment by sethfitz** [comment]
Good question. I'll update the README.

This has been replaced by https://github.com/mojodna/marblecutter-openaerialmap

https://github.com/mojodna/marblecutter-virtual is useful if you want to tile remote images w/o the OAM metadata.
